
import "./globals.css";
import Providers from "./providers"; 

export const metadata = {
  title: "Aim Tune",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR">
      <body className="antialiased">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
