import "./globals.css";
import Providers from "./providers";
import StyledComponentsRegistry from "./styled-registry"; 
import { Poppins } from 'next/font/google';

export const metadata = {
  title: "Aim Tune",
  description: "Generated by create next app",
  icons: {
    icon: '/alvovermelho.png', 
  },
};

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '600', '700'], 
  variable: '--font-poppins',   
});

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR" className={poppins.className}>
      <body className="antialiased">
        <StyledComponentsRegistry>
          <Providers>{children}</Providers>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}