import "./globals.css";
import Providers from "./providers";
import StyledComponentsRegistry from "./styled-registry"; 

export const metadata = {
  title: "Aim Tune",
  description: "Generated by create next app",
  icons: {
    icon: '/alvovermelho.png', 
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR">
      <body className="antialiased">
        <StyledComponentsRegistry>
          <Providers>{children}</Providers>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
